// File generated by FlutterFire CLI. Run `flutterfire configure` to overwrite.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'DefaultFirebaseOptions have not been configured. '
      'Run "flutterfire configure" in the admin_panel directory.',
    );
  }
}
